---
title: "ConsultingUpload"
output: html_document
---


```{r, include=FALSE}
library(mosaic)
library(ResourceSelection) 
library(car)
library(tidyverse)
library(DT)
library(pander)
library(ggplot2)
library(readr)
library(stringr)
```

## R Markdown

```{r cars}
lab <- read_csv("C:/Users/user/OneDrive/Desktop/Stats stuff/325 book/Statistics-Notebook-master/CenterVisitReport (20).csv")
labmin <- lab %>%
  rename(Course = `Course`,
         Professor = `Professor`,
         Slot_type = `Slot type`,
         Students_class = `Student's class`,
         Student_type = `Student's type`,
         Visit_duration = `Visit duration (in minutes)`,
         DateTime = `Date (of the appointment/visit)`,
         Status = `Status (of the appointment/visit)`)

#labmin <- filter(lab, `Visit_duration` >= 1)

Slist <- c("MATH 221A", "MATH 221B", "MATH 221C", "MATH 325", "MATH 425", "MATH 326")
Mlist <- c("MATH 100A", "MATH 100B", "MATH 101", "MATH 108X", "MATH 109", "MATH 110X", "MATH 111", "MATH 112X", "MATH 113", "MATH 119", "MATH 191", "MATH 205", "MATH 214","MATH 215", "MATH 275", "MATH 280", "MATH 316", "MATH 330", "MATH 340", "MATH 341", "MATH 350")
labmin$DateTimeFor <- as.POSIXlt(labmin$DateTime, tz = "MST", format = "%m/%d/%Y %H:%M",
           tryFormats = c("%Y-%m-%d %H:%M:%OS",
                          "%Y/%m/%d %H:%M:%OS",
                          "%Y-%m-%d %H:%M",
                          "%m/%d/%Y %H:%M",
                          "%Y-%m-%d",
                          "%Y/%m/%d"))


labmin$Day_of_week <- weekdays(as.Date(labmin$DateTimeFor))
labmin$Dur_LT_one <- case_when(labmin$Visit_duration < 1 ~ 1, labmin$Visit_duration >= 1 ~ 0)
filteredstuff <- filter(labmin, (labmin$Course %in% Slist == TRUE),
                        (labmin$Dur_LT_one == 0))
MuStats <- mean(filteredstuff$Visit_duration)
filteredstuff <- filter(labmin, (labmin$Course %in% Mlist == TRUE),
                        (labmin$Dur_LT_one == 0))
MuNonStats <- mean(labmin$Visit_duration)
filteredstuff <- filter(labmin, (labmin$Course %in% Slist == FALSE & labmin$Course %in% Mlist == FALSE),
                        (labmin$Dur_LT_one == 0))
MuNonMath <- mean(labmin$Visit_duration)
#c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", 
#   "Friday", "Saturday")[as.POSIXlt(df$date)$wday + 1]
```


```{r}
library(tidyr)
library(stringr)

#labmindi <- filter(labmin, labmin$`Slot_type`== "DropIn")
#labmin <-labmin
#labmin <- drop_na(labmin$Course)
labmin <- labmin[!is.na(labmin$Course),]
labmin <- select(labmin, -X9)

labmin$nonmath <- case_when(labmin$`Course` %in% Slist == FALSE & labmin$`Course` %in% Mlist == FALSE ~ 1, labmin$`Course` %in% Slist == TRUE | labmin$`Course` %in% Mlist == TRUE ~ 0)
labmin$Check_In <- format(as.POSIXct(labmin$DateTimeFor), format = "%H:%M")
labmin$Date <- format(as.POSIXct(labmin$DateTimeFor), format = "%Y-%m-%d")
labmin$Day_of_week <- factor(labmin$Day_of_week)

labmin$`Visit_duration` <- case_when(labmin$`Course` %in% Slist == TRUE & (labmin$`Visit_duration` ==60 | labmin$`Visit_duration` < 1) ~ MuStats, 
                                     labmin$`Course` %in% Mlist == TRUE & (labmin$`Visit_duration` ==60 | labmin$`Visit_duration` < 1) ~ MuNonStats, 
                                     labmin$`Course` %in% Mlist == FALSE & labmin$`Course` %in% Slist == FALSE & (labmin$`Visit_duration` ==60 | labmin$`Visit_duration` < 1) ~ MuNonMath, 
                                     labmin$`Visit_duration` !=60 ~ labmin$`Visit_duration` )
#labmin$Check_In <-substr(labmin$Check_In, start = 1, stop = 2)
hour <- as.numeric(substr(labmin$Check_In, start = 0, stop = 2))
min <- (1.6666667 * as.numeric(substr(labmin$Check_In, start = 4, stop = 5)))/100
labmin$checkinNum <- hour + min


labmindp <-labmin
#find Q1, Q3, and interquartile range for values in column family
Q1 <- quantile(labmindp$Visit_duration, .25, na.rm = TRUE)
Q3 <- quantile(labmindp$Visit_duration, .75, na.rm = TRUE)
IQR <- IQR(labmindp$`Visit_duration`, na.rm = TRUE)


#only keep rows in dataframe that have values within 1.5*IQR of Q1 and Q3
LCD <- subset(labmindp, labmindp$`Visit_duration`> (Q1 - 1.5*IQR) & labmindp$`Visit_duration`< (Q3 + 1.5*IQR))



#LCD$stats <- case_when(LCD$`Course` %in% Slist == TRUE ~ 1, LCD$`Course` %in% Mlist == TRUE  ~ 0 )





LCDAVG <- LCD


LCDISD <- filter(LCD, LCD$`Course` %in% Slist == TRUE)
LCDNSD <- filter(LCD, LCD$`Course` %in% Mlist == TRUE)
LCDNMath <- filter(LCD, LCD$`Course` %in% Mlist == FALSE & LCD$`Course` %in% Slist == FALSE)

```